security:
  enable_authenticator_manager: true
  # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    App\Entity\User:
      algorithm: auto

  role_hierarchy:
    ROLE_USER:
      - ROLE_USER
    ROLE_ADMIN:
      - ROLE_ADMIN
      - ROLE_ADMIN_OWNER
    ROLE_ADMIN_OWNER:
      - ROLE_SUPER_ADMIN
      - ROLE_ADMIN_OWNER_GET
      - ROLE_ADMIN_OWNER_POST
      - ROLE_ADMIN_OWNER_PUT
      - ROLE_ADMIN_OWNER_DELETE

      # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
  providers:
    # used to reload user from session & other features (e.g. switch_user)
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email

    # used to reload user from session & other features (e.g. switch_user)
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    login:
      pattern: ^/api/login
      stateless: true
      provider: app_user_provider
      json_login:
        check_path: /api/login_check # or api_login_check as defined in config/routes.yaml
        success_handler: lexik_jwt_authentication.handler.authentication_success
        failure_handler: lexik_jwt_authentication.handler.authentication_failure
        username_path: email

    api:
      pattern: ^/api
      stateless: true
      jwt: ~

    main:
      lazy: true
      provider: app_user_provider
      custom_authenticator: App\Security\AppCustomAuthenticator
        # configure the maximum login attempts in a custom period of time
      login_throttling:
        max_attempts: 3
        interval: '15 minutes'
      logout:
        path: app_logout
        # where to redirect after logout
        # target: app_any_route

      # activate different ways to authenticate
      # https://symfony.com/doc/current/security.html#the-firewall

      # https://symfony.com/doc/current/security/impersonating_user.html
      # switch_user: true

  # Easy way to control access for large sections of your site
  # Note: Only the *first* access control that matches will be used
  access_control:
  # - { path: ^/admin, roles: ROLE_ADMIN }
  # - { path: ^/profile, roles: ROLE_USER }
    - { path: '^/user', roles: [IS_AUTHENTICATED_FULLY, ROLE_ADMIN] }
